# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Thesis API
  description: Explore the magical world!
  version: "1.0.0"
# the domain of the service
host: localhost:80
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /objects:
    get:
      summary: Objects
      description: |
        The Objects endpoint returns information about the in-game objects
        near a given location. The response includes the buildings and monsters.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Objects
        - Location
      responses:
        200:
          description: An array of all game objects
          schema:
            type: array
            items:
              $ref: '#/definitions/Objects'
        403:
          description: Permission Denied
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /objects/buildings:
    get:
      summary: Buildings
      description: |
        The Buildings endpoint returns information about in-game *buildings*
        near a given location. The response includes the display name
        and other details about each building.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Objects
        - Buildings
        - Location
      responses:
        200:
          description: An array of buildings
          schema:
            type: array
            items:
              $ref: '#/definitions/Building'
        403:
          description: Permission Denied
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /objects/monsters:
    get:
      summary: Monsters
      description: |
        The Monsters endpoint returns information about in-game *buildings*
        near a given location. The response includes the display name
        and other details about each monster.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - Objects
        - Monsters
        - Location
      responses:
        200:
          description: An array of monsters
          schema:
            type: array
            items:
              $ref: '#/definitions/Monster'
        403:
          description: Permission Denied
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/distance:
    get:
      summary: Distance Traveled
      description: |
        The Distance endpoint returns distance traveled by the user. The response includes distance for various timespans. 
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
      tags:
        - User
        - Location
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Distances'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Objects:
    type: object
    properties:
      buildings:
        type: array
        items:
          $ref: '#/definitions/Building'
      monsters:
        type: array
        items:
          $ref: '#/definitions/Monster'  
  Building:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
  Monster:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      display_name:
        type: string
        description: Display name of product.
      estimate:
        type: string
        description: Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or "Metered" for TAXI.
      low_estimate:
        type: number
        description: Lower bound of the estimated price.
      high_estimate:
        type: number
        description: Upper bound of the estimated price.
      surge_multiplier:
        type: number
        description: Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
  Distances:
    type: object
    properties:
      day:
        type: number
        format: double
        description: Distance traveled today.
      week:
        type: number
        format: double
        description: Distance traveled this week.
      month:
        type: number
        format: double
        description: Distance traveled this month.
      year:
        type: number
        format: double
        description: Distance traveled this year.
      total:
        type: number
        format: double
        description: Distance traveled in total.
  Profile:
    type: object
    properties:
      first_name:
        type: string
        description: First name of the Uber user.
      last_name:
        type: string
        description: Last name of the Uber user.
      email:
        type: string
        description: Email address of the Uber user
      picture:
        type: string
        description: Image URL of the Uber user.
      promo_code:
        type: string
        description: Promo code of the Uber user.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
